Setup

In [153]:
import reader

spreadsheet = "FPL.xlsx"

dataframes = reader.read_spreadsheet(spreadsheet, 21)

players_verbose = dataframes["Players"]
teams = dataframes["Teams"]
games = dataframes["Games"]
fixtures = dataframes["Fixtures"]

players = reader.simplify_players(players_verbose)

upcoming_gameweek = reader.get_upcoming_gameweek(games)

In [154]:
import fixture_analyser as fa

all_multipliers = fa.get_all_upcoming_multipliers(fixtures, teams, 5, upcoming_gameweek)

top_attacking_teams = all_multipliers.sort_values("Attacking Multiplier", ascending=False).head(10)[["Attacking Multiplier"]]
top_defending_teams = all_multipliers.sort_values("Defending Multiplier", ascending=False).head(10)[["Defending Multiplier"]]

post_quality_players = fa.apply_fixture_multipliers(players, fixtures, teams, 5, upcoming_gameweek, fixture_weighting=0.6)

top_players = post_quality_players.head(20)
top_three_per_team = post_quality_players.groupby("Team").head(3)

target_attacking_players = post_quality_players[post_quality_players["Pos."].isin(["FWD", "MID"])]
target_attacking_players = target_attacking_players[target_attacking_players["Team"].isin(list(top_attacking_teams.index.values))]
target_attacking_players = target_attacking_players.groupby("Team").head(3)

target_defending_players = post_quality_players[post_quality_players["Pos."].isin(["DEF", "GKP"])]
target_defending_players = target_defending_players[target_defending_players["Team"].isin(list(top_defending_teams.index.values))]
target_defending_players = target_defending_players.groupby("Team").head(3)

In [155]:
import squad_generation as sg
import pandas as pd

targets = pd.concat([target_attacking_players, target_attacking_players])
targets_squad = sg.gen_squad(targets, 5)

## **Best Attacking Fixtures**

In [156]:
top_attacking_teams

      Attacking Multiplier
Team
MCI                   9.18
LIV                   9.04
CHE                   7.89
TOT                   7.08
ARS                   6.94
LEI                   6.53
BRE                   6.33
MUN                   6.03
BHA                   6.00
AVL                   5.71

## **Best Defending Fixtures**

In [157]:
top_defending_teams

      Defending Multiplier
Team
MCI                   9.19
LIV                   9.14
CHE                   7.51
TOT                   6.82
WOL                   6.73
BHA                   6.34
ARS                   6.12
BRE                   5.69
CRY                   5.37
AVL                   5.36

## **Best Players**

In [158]:
top_players

                  Post Quality  Quality Pos. Team  Price
Player
Salah                    49.01     6.26  MID  LIV  13.00
Haaland                  47.44     6.00  FWD  MCI  11.50
Chillwell                44.19     6.40  DEF  CHE   6.00
Alexander-Arnold         43.73     5.54  DEF  LIV   7.50
Cancelo                  40.55     5.12  DEF  MCI   7.00
van Dijk                 39.28     4.98  DEF  LIV   6.50
Son                      36.10     5.43  MID  TOT  12.00
Robertson                35.28     4.47  DEF  LIV   7.00
Laporte                  34.41     4.35  DEF  MCI   6.00
Matip                    33.57     4.26  DEF  LIV   6.00
Dias                     33.18     4.19  DEF  MCI   6.00
Alisson                  32.40     4.11  GKP  LIV   5.50
Kane                     32.32     4.86  FWD  TOT  11.50
Ederson                  32.07     4.05  GKP  MCI   5.50
Nunez                    31.31     4.00  FWD  LIV   9.00
De Bruyne                30.99     3.92  MID  MCI  12.00
Sterling                 29.90     3.78  MID  MCI  10.00
Foden                    28.72     3.63  MID  MCI   8.00
Jota                     28.23     3.61  FWD  LIV   9.00
Thiago                   28.16     3.60  MID  LIV   5.50

## **Attacking Targets**

The top 3 attacking players of teams with best attacking fixtures

In [159]:
target_attacking_players

            Post Quality  Quality Pos. Team  Price
Player
Salah              49.01     6.26  MID  LIV  13.00
Haaland            47.44     6.00  FWD  MCI  11.50
Son                36.10     5.43  MID  TOT  12.00
Kane               32.32     4.86  FWD  TOT  11.50
Nunez              31.31     4.00  FWD  LIV   9.00
De Bruyne          30.99     3.92  MID  MCI  12.00
Sterling           29.90     3.78  MID  MCI  10.00
Jota               28.23     3.61  FWD  LIV   9.00
Vardy              26.78     4.24  FWD  LEI   9.50
Mount              26.36     3.69  MID  CHE   8.00
Ronaldo            26.33     4.38  FWD  MUN  10.50
Saka               26.26     4.00  MID  ARS   8.00
Fernandes          25.36     4.21  MID  MUN  10.00
Kulusevski         25.29     3.80  MID  TOT   8.00
Gallagher          24.20     3.39  MID  CHE   6.00
Odegaard           22.25     3.39  MID  ARS   6.50
Trossard           21.78     3.63  MID  BHA   6.50
Toney              21.77     3.51  FWD  BRE   7.00
Pulisic            20.42     2.86  MID  CHE   6.00
Coutinho           20.34     3.49  MID  AVL   7.00
Tielemans          19.50     3.09  MID  LEI   6.50
Partey             19.16     2.92  MID  ARS   5.00
Maddison           19.01     3.01  MID  LEI   8.00
Mbeumo             18.59     3.00  FWD  BRE   6.00
Watkins            18.57     3.19  FWD  AVL   7.50
Norgaard           18.56     2.99  MID  BRE   5.50
Eriksen            16.70     2.78  MID  MUN   5.00
Welbeck            16.52     2.75  FWD  BHA   6.50
McGinn             15.75     2.70  MID  AVL   5.50
Maupay             13.65     2.28  FWD  BHA   6.50

## **Defending Targets**

The top 3 defending players of teams with best defending fixtures

In [160]:
target_defending_players

                  Post Quality  Quality Pos. Team  Price
Player
Chillwell                44.19     6.40  DEF  CHE   6.00
Alexander-Arnold         43.73     5.54  DEF  LIV   7.50
Cancelo                  40.55     5.12  DEF  MCI   7.00
van Dijk                 39.28     4.98  DEF  LIV   6.50
Robertson                35.28     4.47  DEF  LIV   7.00
Laporte                  34.41     4.35  DEF  MCI   6.00
Dias                     33.18     4.19  DEF  MCI   6.00
Sessegnon                27.93     4.30  DEF  TOT   4.50
Dier                     27.88     4.30  DEF  TOT   5.00
James                    26.72     3.87  DEF  CHE   6.00
Perisic                  25.96     4.00  DEF  TOT   5.50
Mendy                    25.18     3.65  GKP  CHE   5.00
Tierney                  24.14     3.97  DEF  ARS   5.00
Gabriel                  22.75     3.75  DEF  ARS   5.00
Cash                     22.72     4.05  DEF  AVL   5.00
Cucurella                22.60     3.64  DEF  BHA   5.00
Dunk                     22.34     3.60  DEF  BHA   4.50
Coady                    22.18     3.45  DEF  WOL   5.00
Kilman                   21.97     3.41  DEF  WOL   4.50
Jansson                  20.65     3.55  DEF  BRE   4.50
White                    20.38     3.36  DEF  ARS   4.50
Guehi                    19.92     3.54  DEF  CRY   4.50
Sanchez                  19.79     3.19  GKP  BHA   4.50
Sa                       19.55     3.04  GKP  WOL   5.00
Raya                     19.39     3.33  GKP  BRE   4.50
Mings                    18.63     3.32  DEF  AVL   4.50
Martinez                 17.61     3.14  GKP  AVL   5.00
Henry                    17.59     3.02  DEF  BRE   4.50
Andersen                 17.34     3.08  DEF  CRY   4.50
Mitchell                 17.11     3.04  DEF  CRY   4.50

## **Squad of Targets**

In [161]:
targets_squad

          Post Quality Quality Pos. Team Price
Player
Salah            49.01    6.26  MID  LIV 13.00
Haaland          47.44    6.00  FWD  MCI 11.50
Son              36.10    5.43  MID  TOT 12.00
Kane             32.32    4.86  FWD  TOT 11.50
Nunez            31.31    4.00  FWD  LIV  9.00
De Bruyne        30.99    3.92  MID  MCI 12.00
Gallagher        24.20    3.39  MID  CHE  6.00
Partey           19.16    2.92  MID  ARS  5.00

## **Bargains**

In [162]:
bargains = post_quality_players.copy()

bargains["Quality per Mil"] = bargains.apply(lambda row: row["Post Quality"] / row["Price"], axis=1)
bargains = bargains.sort_values("Quality per Mil", ascending=False)
bargains.head(20)

                  Post Quality  Quality Pos. Team  Price  Quality per Mil
Player
Chillwell                44.19     6.40  DEF  CHE   6.00             7.37
Sessegnon                27.93     4.30  DEF  TOT   4.50             6.21
van Dijk                 39.28     4.98  DEF  LIV   6.50             6.04
Alisson                  32.40     4.11  GKP  LIV   5.50             5.89
Alexander-Arnold         43.73     5.54  DEF  LIV   7.50             5.83
Ederson                  32.07     4.05  GKP  MCI   5.50             5.83
Cancelo                  40.55     5.12  DEF  MCI   7.00             5.79
Laporte                  34.41     4.35  DEF  MCI   6.00             5.73
Matip                    33.57     4.26  DEF  LIV   6.00             5.60
Dier                     27.88     4.30  DEF  TOT   5.00             5.58
Dias                     33.18     4.19  DEF  MCI   6.00             5.53
Thiago                   28.16     3.60  MID  LIV   5.50             5.12
Robertson                35.28     4.47  DEF  LIV   7.00             5.04
Mendy                    25.18     3.65  GKP  CHE   5.00             5.04
Dunk                     22.34     3.60  DEF  BHA   4.50             4.96
Kilman                   21.97     3.41  DEF  WOL   4.50             4.88
Tierney                  24.14     3.97  DEF  ARS   5.00             4.83
Reguilon                 21.35     3.29  DEF  TOT   4.50             4.74
Perisic                  25.96     4.00  DEF  TOT   5.50             4.72
Jansson                  20.65     3.55  DEF  BRE   4.50             4.59

## **Best Squad**

In [163]:
sg.gen_squad(post_quality_players, 4.5)

                 Post Quality Quality Pos. Team Price
Player
Salah                   49.01    6.26  MID  LIV 13.00
Haaland                 47.44    6.00  FWD  MCI 11.50
Chillwell               44.19    6.40  DEF  CHE  6.00
Alexander-Arnold        43.73    5.54  DEF  LIV  7.50
Cancelo                 40.55    5.12  DEF  MCI  7.00
van Dijk                39.28    4.98  DEF  LIV  6.50
Laporte                 34.41    4.35  DEF  MCI  6.00
Mendy                   25.18    3.65  GKP  CHE  5.00
Gallagher               24.20    3.39  MID  CHE  6.00
Sanchez                 19.79    3.19  GKP  BHA  4.50
Skipp                   14.40    2.17  MID  TOT  4.50
Moder                   12.26    2.04  MID  BHA  4.50
Chalobah                11.18    2.00  MID  FUL  4.50
Taylor                  10.53    2.00  FWD  FOR  4.50

In [164]:
pool = pd.concat([post_quality_players.head(20), bargains.loc[bargains["Price"] <= 5]])
sg.gen_squad(pool, 4.5)

                 Post Quality Quality Pos. Team Price
Player
Salah                   49.01    6.26  MID  LIV 13.00
Haaland                 47.44    6.00  FWD  MCI 11.50
Chillwell               44.19    6.40  DEF  CHE  6.00
Alexander-Arnold        43.73    5.54  DEF  LIV  7.50
Cancelo                 40.55    5.12  DEF  MCI  7.00
van Dijk                39.28    4.98  DEF  LIV  6.50
Laporte                 34.41    4.35  DEF  MCI  6.00
Mendy                   25.18    3.65  GKP  CHE  5.00
Kante                   19.96    2.80  MID  CHE  5.00
Sanchez                 19.79    3.19  GKP  BHA  4.50
Partey                  19.16    2.92  MID  ARS  5.00
Eriksen                 16.70    2.78  MID  MUN  5.00
Skipp                   14.40    2.17  MID  TOT  4.50
Taylor                  10.53    2.00  FWD  FOR  4.50

In [165]:
def consider_by_price_points(pool: pd.DataFrame, pos: str, price_points: list[float], players_per_price: int) -> pd.DataFrame:
    players_in_pos = pool.loc[pool["Pos."] == pos]

    players_price_points = []
    for i in range(len(price_points)):
        players_price_points.append(players_in_pos.loc[(players_in_pos["Price"] < price_points[i]) & (players_in_pos["Price"] > price_points[i-1])].head(players_per_price))

    return pd.concat(players_price_points)

In [166]:
from dataclasses import dataclass, field

@dataclass
class PlayerCollection:
    players: pd.DataFrame
    total_price: float = field(init=False)
    total_post_quality: float = field(init=False)
    teams: list[str] = field(init=False)

    def __post_init__(self):
        self.total_price = self.players["Price"].sum()
        self.total_post_quality = self.players["Post Quality"].sum()
        self.teams = self.players["Team"].tolist()

In [167]:
from itertools import combinations

def get_player_collections(pool: pd.DataFrame, amount_to_select: int) -> list[PlayerCollection]:
    collections = []

    for index in list(combinations(pool.index, amount_to_select)):
        collections.append(PlayerCollection(pool.loc[index,:]))

    return collections

In [168]:
def pos_collections_by_price(pool: pd.DataFrame, pos: str, amount_to_select: int, price_points: list[float], players_per_price: int) -> list[PlayerCollection]:
    by_price_points = consider_by_price_points(pool, pos, price_points, players_per_price)
    collections = get_player_collections(by_price_points, amount_to_select)

    return collections

In [173]:
from itertools import product

def possible_outfield_eleven(pool: pd.DataFrame, formation: list[int], price_points: list[float], players_per_price: int, max_price: float) -> pd.DataFrame:

    defs_collections = pos_collections_by_price(pool, "DEF", formation[0], price_points, players_per_price)
    mids_collections = pos_collections_by_price(pool, "MID", formation[1], price_points, players_per_price)
    fwds_collections = pos_collections_by_price(pool, "FWD", formation[2], price_points, players_per_price)

    possible_elevens = product(defs_collections, mids_collections, fwds_collections)

    best_post_quality = 0
    best_squad = []

    for defs, mids, fwds in possible_elevens:
        defs.players.drop_duplicates(inplace=True)
        mids.players.drop_duplicates(inplace=True)
        fwds.players.drop_duplicates(inplace=True)

        if defs.players.shape[0] == formation[0] and mids.players.shape[0] == formation[1] and fwds.players.shape[0] == formation[2]:
            if defs.total_price + mids.total_price + fwds.total_price <= max_price:
                total_teams = defs.teams + mids.teams + fwds.teams
                team_count = [total_teams.count(i) for i in total_teams]

                if max(team_count) <= 3:
                    post_quality = defs.total_post_quality + mids.total_post_quality + fwds.total_post_quality

                    if post_quality > best_post_quality:
                        best_squad = [defs, mids, fwds]
                        best_post_quality = post_quality
    
    return pd.concat([position.players for position in best_squad])

In [191]:
first_team_not_gkp_price = 75
price_points = [5.0, 7.0, 10.0, 14.0]
players_per_price = 3
#formation = [4, 4, 2]

blacklist = ["Thiago", "Gallagher", "Fabinho", "Rodri", "Pulisic"]

consider = post_quality_players.drop(index=blacklist)

In [192]:
b = possible_outfield_eleven(consider, [5, 4, 1], [5.0, 6.5, 8.5, 10.0, 14.0], 3, first_team_not_gkp_price)
print(b["Post Quality"].sum())
b

346.16472219482364

                  Post Quality  Quality Pos. Team  Price
Player
Chillwell                44.19     6.40  DEF  CHE   6.00
Laporte                  34.41     4.35  DEF  MCI   6.00
Alexander-Arnold         43.73     5.54  DEF  LIV   7.50
Cancelo                  40.55     5.12  DEF  MCI   7.00
Robertson                35.28     4.47  DEF  LIV   7.00
Bentancur                19.93     3.00  MID  TOT   5.50
Bernardo                 27.95     3.54  MID  MCI   7.00
Mount                    26.36     3.69  MID  CHE   8.00
Salah                    49.01     6.26  MID  LIV  13.00
Bamford                  24.76     4.43  FWD  LEE   7.50

In [195]:
b = possible_outfield_eleven(consider, [5, 5, 3], [5.0, 6.5, 8.5, 10.0, 14.0], 3, 91)
print(b["Post Quality"].sum())
b

394.65815297672435

                  Post Quality  Quality Pos. Team  Price
Player
Chillwell                44.19     6.40  DEF  CHE   6.00
Laporte                  34.41     4.35  DEF  MCI   6.00
Matip                    33.57     4.26  DEF  LIV   6.00
Alexander-Arnold         43.73     5.54  DEF  LIV   7.50
Cancelo                  40.55     5.12  DEF  MCI   7.00
Bentancur                19.93     3.00  MID  TOT   5.50
Jorginho                 19.60     2.75  MID  CHE   6.00
Bernardo                 27.95     3.54  MID  MCI   7.00
Mount                    26.36     3.69  MID  CHE   8.00
Salah                    49.01     6.26  MID  LIV  13.00
Mbeumo                   18.59     3.00  FWD  BRE   6.00
Undav                    12.00     2.00  FWD  BHA   5.50
Bamford                  24.76     4.43  FWD  LEE   7.50

In [194]:
post_quality_players.loc[(post_quality_players["Pos."] == "MID") & (post_quality_players["Price"] <= 5.5)].head(20)

             Post Quality  Quality Pos. Team  Price
Player
Thiago              28.16     3.60  MID  LIV   5.50
Fabinho             20.88     2.67  MID  LIV   5.50
Kante               19.96     2.80  MID  CHE   5.00
Bentancur           19.93     3.00  MID  TOT   5.50
Henderson           19.42     2.48  MID  LIV   5.50
Partey              19.16     2.92  MID  ARS   5.00
Carvalho            18.78     2.40  MID  LIV   5.00
Norgaard            18.56     2.99  MID  BRE   5.50
Hojbjerg            18.44     2.77  MID  TOT   5.50
Kovacic             17.15     2.40  MID  CHE   5.00
Eriksen             16.70     2.78  MID  MUN   5.00
Fornals             16.68     2.86  MID  WHU   5.50
Soucek              16.45     2.82  MID  WHU   5.50
McGinn              15.75     2.70  MID  AVL   5.50
Xhaka               15.65     2.39  MID  ARS   5.00
Hudson-Odoi         14.99     2.10  MID  CHE   5.50
Phillips            14.83     1.88  MID  MCI   5.00
Elliott             14.53     1.86  MID  LIV   5.00
Skipp               14.40     2.17  MID  TOT   4.50
Kamara              13.98     2.40  MID  AVL   5.00