Setup

In [1]:
import reader

spreadsheet = "FPL.xlsx"

dataframes = reader.read_spreadsheet(spreadsheet, 21)

players_verbose = dataframes["Players"]
teams = dataframes["Teams"]
games = dataframes["Games"]
fixtures = dataframes["Fixtures"]

players = reader.simplify_players(players_verbose)

upcoming_gameweek = reader.get_upcoming_gameweek(games)

In [2]:
import fixture_analyser as fa

all_multipliers = fa.get_all_upcoming_multipliers(fixtures, teams, 5, upcoming_gameweek)

top_attacking_teams = all_multipliers.sort_values("Attacking Multiplier", ascending=False).head(10)[["Attacking Multiplier"]]
top_defending_teams = all_multipliers.sort_values("Defending Multiplier", ascending=False).head(10)[["Defending Multiplier"]]

post_quality_players = fa.apply_fixture_multipliers(players, fixtures, teams, 5, upcoming_gameweek)

top_players = post_quality_players.head(20)
top_three_per_team = post_quality_players.groupby("Team").head(3)

target_attacking_players = post_quality_players[post_quality_players["Pos."].isin(["FWD", "MID"])]
target_attacking_players = target_attacking_players[target_attacking_players["Team"].isin(list(top_attacking_teams.index.values))]
target_attacking_players = target_attacking_players.groupby("Team").head(3)

target_defending_players = post_quality_players[post_quality_players["Pos."].isin(["DEF", "GKP"])]
target_defending_players = target_defending_players[target_defending_players["Team"].isin(list(top_defending_teams.index.values))]
target_defending_players = target_defending_players.groupby("Team").head(3)

In [3]:
import squad_generation as sg
import pandas as pd

targets = pd.concat([target_attacking_players, target_attacking_players])
targets_squad = sg.gen_squad(targets, 5)

## **Best Attacking Fixtures**

In [4]:
top_attacking_teams

      Attacking Multiplier
Team
MCI                   9.18
LIV                   9.04
CHE                   7.89
TOT                   7.08
ARS                   6.94
LEI                   6.53
BRE                   6.33
MUN                   6.03
BHA                   6.00
AVL                   5.71

## **Best Defending Fixtures**

In [5]:
top_defending_teams

      Defending Multiplier
Team
MCI                   9.19
LIV                   9.14
CHE                   7.51
TOT                   6.82
WOL                   6.73
BHA                   6.34
ARS                   6.12
BRE                   5.69
CRY                   5.37
AVL                   5.36

## **Best Players**

In [6]:
top_players

                  Post Quality  Quality Pos. Team  Price
Player
Salah                    56.64     6.26  MID  LIV     12
Haaland                  55.06     6.00  FWD  MCI     11
Alexander-Arnold         50.71     5.54  DEF  LIV      8
Chillwell                48.05     6.40  DEF  CHE      6
Cancelo                  47.09     5.12  DEF  MCI      7
van Dijk                 45.55     4.98  DEF  LIV      6
Mane                     44.41     4.91  MID  LIV      8
Robertson                40.90     4.47  DEF  LIV      6
Jota                     39.97     4.42  MID  LIV      6
Laporte                  39.95     4.35  DEF  MCI      6
Matip                    38.93     4.26  DEF  LIV      6
Dias                     38.52     4.19  DEF  MCI      8
Son                      38.45     5.43  MID  TOT     10
Alisson                  37.57     4.11  GKP  LIV      5
Ederson                  37.23     4.05  GKP  MCI      6
Nunez                    36.18     4.00  FWD  LIV      7
De Bruyne                35.97     3.92  MID  MCI     12
Sterling                 34.70     3.78  MID  MCI      8
Kane                     34.43     4.86  FWD  TOT     12
Foden                    33.34     3.63  MID  MCI      8

## **Attacking Targets**

The top 3 attacking players of teams with best attacking fixtures

In [7]:
target_attacking_players

            Post Quality  Quality Pos. Team  Price
Player
Salah              56.64     6.26  MID  LIV     12
Haaland            55.06     6.00  FWD  MCI     11
Mane               44.41     4.91  MID  LIV      8
Jota               39.97     4.42  MID  LIV      6
Son                38.45     5.43  MID  TOT     10
De Bruyne          35.97     3.92  MID  MCI     12
Sterling           34.70     3.78  MID  MCI      8
Kane               34.43     4.86  FWD  TOT     12
Mount              29.16     3.69  MID  CHE      6
Saka               27.75     4.00  MID  ARS      6
Vardy              27.68     4.24  FWD  LEI     10
Kulusevski         26.94     3.80  MID  TOT      6
Ronaldo            26.38     4.38  FWD  MUN     12
Fernandes          25.41     4.21  MID  MUN     10
Havertz            24.44     3.10  MID  CHE      5
Odegaard           23.52     3.39  MID  ARS      6
Pulisic            22.58     2.86  MID  CHE      5
Toney              22.25     3.51  FWD  BRE      6
Mbeumo             22.08     3.49  MID  BRE      5
Trossard           21.78     3.63  MID  BHA      6
Partey             20.25     2.92  MID  ARS      5
Tielemans          20.15     3.09  MID  LEI      6
Coutinho           19.94     3.49  MID  AVL      8
Maddison           19.65     3.01  MID  LEI      6
Norgaard           18.96     2.99  MID  BRE      5
Watkins            18.20     3.19  FWD  AVL      6
Kamara             17.14     3.00  MID  AVL      6
Welbeck            16.52     2.75  FWD  BHA      5
Sancho             13.95     2.31  MID  MUN      8
Maupay             13.66     2.28  FWD  BHA      5

## **Defending Targets**

The top 3 defending players of teams with best defending fixtures

In [8]:
target_defending_players

                  Post Quality  Quality Pos. Team  Price
Player
Alexander-Arnold         50.71     5.54  DEF  LIV      8
Chillwell                48.05     6.40  DEF  CHE      6
Cancelo                  47.09     5.12  DEF  MCI      7
van Dijk                 45.55     4.98  DEF  LIV      6
Robertson                40.90     4.47  DEF  LIV      6
Laporte                  39.95     4.35  DEF  MCI      6
Dias                     38.52     4.19  DEF  MCI      8
Sessegnon                29.33     4.30  DEF  TOT      8
Dier                     29.28     4.30  DEF  TOT      8
James                    29.05     3.87  DEF  CHE      6
Mendy                    27.37     3.65  GKP  CHE      6
Perisic                  27.27     4.00  DEF  TOT      7
Tierney                  24.33     3.97  DEF  ARS      6
Coady                    23.19     3.45  DEF  WOL      6
Cucurella                23.09     3.64  DEF  BHA      6
Kilman                   22.97     3.41  DEF  WOL      6
Gabriel                  22.94     3.75  DEF  ARS      6
Dunk                     22.83     3.60  DEF  BHA      5
Cash                     21.68     4.05  DEF  AVL      6
White                    20.55     3.36  DEF  ARS      5
Sa                       20.44     3.04  GKP  WOL      6
Sanchez                  20.22     3.19  GKP  BHA      5
Jansson                  20.22     3.55  DEF  BRE      6
Guehi                    19.03     3.54  DEF  CRY      6
Raya                     18.98     3.33  GKP  BRE      5
Mings                    17.78     3.32  DEF  AVL      6
Henry                    17.22     3.02  DEF  BRE      5
Martinez                 16.80     3.14  GKP  AVL      6
Andersen                 16.57     3.08  DEF  CRY      5
Mitchell                 16.34     3.04  DEF  CRY      5

## **Squad of Targets**

In [9]:
targets_squad

          Post Quality Quality Pos. Team Price
Player
Salah            56.64    6.26  MID  LIV    12
Haaland          55.06    6.00  FWD  MCI    11
Mane             44.41    4.91  MID  LIV     8
Jota             39.97    4.42  MID  LIV     6
Son              38.45    5.43  MID  TOT    10
De Bruyne        35.97    3.92  MID  MCI    12
Kane             34.43    4.86  FWD  TOT    12
Toney            22.25    3.51  FWD  BRE     6

## **Bargains**

In [10]:
bargains = post_quality_players.copy()

bargains["Quality per Mil"] = bargains.apply(lambda row: row["Post Quality"] / row["Price"], axis=1)
bargains = bargains.sort_values("Quality per Mil", ascending=False)
bargains.head(20)

                  Post Quality  Quality Pos. Team  Price  Quality per Mil
Player
Chillwell                48.05     6.40  DEF  CHE      6             8.01
van Dijk                 45.55     4.98  DEF  LIV      6             7.59
Alisson                  37.57     4.11  GKP  LIV      5             7.51
Robertson                40.90     4.47  DEF  LIV      6             6.82
Cancelo                  47.09     5.12  DEF  MCI      7             6.73
Jota                     39.97     4.42  MID  LIV      6             6.66
Laporte                  39.95     4.35  DEF  MCI      6             6.66
Thiago                   32.54     3.60  MID  LIV      5             6.51
Bernardo                 32.45     3.54  MID  MCI      5             6.49
Matip                    38.93     4.26  DEF  LIV      6             6.49
Alexander-Arnold         50.71     5.54  DEF  LIV      8             6.34
Ederson                  37.23     4.05  GKP  MCI      6             6.21
Gundogan                 29.34     3.20  MID  MCI      5             5.87
Diaz                     29.19     3.23  MID  LIV      5             5.84
Mane                     44.41     4.91  MID  LIV      8             5.55
Firmino                  27.25     3.01  FWD  LIV      5             5.45
Carvalho                 27.13     3.00  MID  LIV      5             5.43
Nunez                    36.18     4.00  FWD  LIV      7             5.17
Alonso                   25.56     3.41  DEF  CHE      5             5.11
Azpilicueta              20.44     2.72  DEF  CHE      4             5.11

## **Best Squad**

In [12]:
sg.gen_squad(post_quality_players, 4)

                 Post Quality Quality Pos. Team Price
Player
Salah                   56.64    6.26  MID  LIV    12
Haaland                 55.06    6.00  FWD  MCI    11
Alexander-Arnold        50.71    5.54  DEF  LIV     8
Chillwell               48.05    6.40  DEF  CHE     6
Cancelo                 47.09    5.12  DEF  MCI     7
van Dijk                45.55    4.98  DEF  LIV     6
Laporte                 39.95    4.35  DEF  MCI     6
Son                     38.45    5.43  MID  TOT    10
Mount                   29.16    3.69  MID  CHE     6
Kovacic                 18.97    2.40  MID  CHE     4
Aaronson                15.95    3.00  MID  LEE     4
Horvath                 14.88    3.00  GKP  FOR     4
Gazzaniga               14.34    3.00  GKP  FUL     4
Davis                   14.33    3.00  FWD  FOR     4
Surridge                14.33    3.00  FWD  FOR     4

In [26]:
pool = pd.concat([post_quality_players.head(20), bargains.loc[bargains["Price"] <= 5]])
sg.gen_squad(pool, 4)

                 Post Quality Quality Pos. Team Price
Player
Salah                   56.64    6.26  MID  LIV    12
Haaland                 55.06    6.00  FWD  MCI    11
Alexander-Arnold        50.71    5.54  DEF  LIV     8
Chillwell               48.05    6.40  DEF  CHE     6
Cancelo                 47.09    5.12  DEF  MCI     7
van Dijk                45.55    4.98  DEF  LIV     6
Laporte                 39.95    4.35  DEF  MCI     6
Son                     38.45    5.43  MID  TOT    10
Havertz                 24.44    3.10  MID  CHE     5
Pulisic                 22.58    2.86  MID  CHE     5
Roca                    15.95    3.00  MID  LEE     4
Horvath                 14.88    3.00  GKP  FOR     4
Gazzaniga               14.34    3.00  GKP  FUL     4
Surridge                14.33    3.00  FWD  FOR     4
Taylor                  14.33    3.00  FWD  FOR     4